# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

    needs:
      - call-foo
      - call-bar

  get-versions:
    runs-on: ubuntu-latest
    steps:
      - name: List things
        id: list
        run: |
          echo runner.name is ${{ runner.name }}
          hostname -f && pwd && ls -al
          {
            echo 'FILE_LIST<<EOF'
            # ls -al /etc | tee TESTFILE
            {
              echo one
              echo two
              echo t33
            } | jq -Rn '[inputs]'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
    outputs:
      THE_LIST: ${{ steps.list.outputs.FILE_LIST }}

  show-versions:
    needs:
      - get-versions
    runs-on: ubuntu-latest
    steps:
      - name: List things
        run: |
          echo runner.name is ${{ runner.name }}
          hostname -f && pwd && ls -al
          echo "FILE_LIST is: ${{ needs.get-versions.outputs.THE_LIST }}"


  call-foo:
    uses: ./.github/workflows/manual.yml
    needs:
      - get-versions
    with:
      name: foo
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.THE_LIST) }}


  call-bar:
    # references to workflows must be rooted in '.github/workflows'
    uses: ./.github/workflows/reuse/manual.yml
    with:
      name: bar
    needs:
      - call-foo

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          hostname -f && pwd && ls -al
          ls -al "$GITHUB_OUTPUT"
          echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: |
          hostname -f && pwd && ls -al
          ls -al "$GITHUB_OUTPUT"
          echo "test=world" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: |
          hostname -f && pwd && ls -al
          echo "$OUTPUT1 $OUTPUT2"
